// PLAN ACTIONS
export const UPDATE_PLAN = 'UPDATE_PLAN';
export const REQUEST_PLAN = 'REQUEST_PLAN';
export const REQUEST_PLAN_SUCCESS = 'REQUEST_PLAN_SUCCESS';
export const REQUEST_PLAN_FAILURE = 'REQUEST_PLAN_FAILURE';


// GOOGLE PLACES ACTIONS
export const REQUEST_GOOGLE_PLACES = 'REQUEST_GOOGLE_PLACES';
export const REQUEST_GOOGLE_PLACES_SUCCESS = 'REQUEST_GOOGLE_PLACES_SUCCESS';
export const REQUEST_GOOGLE_PLACES_FAILURE = 'REQUEST_GOOGLE_PLACES_FAILURE';
