// PLAN ACTIONS
export const UPDATE_PLAN = 'UPDATE_PLAN';
export const REQUEST_PLAN = 'REQUEST_PLAN';
export const REQUEST_PLAN_SUCCESS = 'REQUEST_PLAN_SUCCESS';
export const REQUEST_PLAN_FAILURE = 'REQUEST_PLAN_FAILURE';
