// PLAN ACTIONS
export const UPDATE_PLAN = 'UPDATE_PLAN';
export const REQUEST_PLAN = 'REQUEST_PLAN';
export const FETCH_PLANS_ERROR = 'FETCH_PLANS_ERROR';
export const FETCH_PLANS_LOADING = 'FETCH_PLANS_LOADING';
